language: python
python:
  - "3.6"
  - "3.7"
install:
    # Install vcstools
    - pip install .

    # Install codacy
    - pip install coveralls
    - pip install codacy-coverage
    - export CODACY_PROJECT_TOKEN=6a8dcd83c6ab42e5b03ef43d8302dd0a
# command to run tests
script:
    - coverage run setup.py test
after_success:
    - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r .coverage
